name = "OptimalLandUseAllocation"
uuid = "20ea66d4-9f52-11ee-1305-6fda9d8ce5be"
authors = ["Antonello Lobianco <antonello@lobianco.org>, Anais Charis Kanellos <charis.kanellos@inrae.fr>, Philippe Delacote <philippe.delacote@inrae.fr>"]
version = "0.0.1"

[deps]
InfiniteOpt = "20393b10-9daf-11e9-18c9-8db751c92c57"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
